spring.application.name=ligas-api-backend
server.port=8080

# ======================
# DATABASE (PostgreSQL)
# ======================
spring.datasource.url=jdbc:postgresql://dpg-d4iatoodl3ps73a1ivg0-a.oregon-postgres.render.com:5432/pruebas_lsnc?sslmode=require
spring.datasource.username=pruebas_lsnc_user
spring.datasource.password=WLuUg7SClyu3rtniLczD98JOY6xwIJHi
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=drop-create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opcional (Hibernate normalmente lo detecta solo)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ======================
# JWT
# ======================
app.jwt.secret=PFqFNJ7AAzYVu6uROYEfKlfso8ha0TTJW/KGfzk4F620VdEOdxJTsMIjjRRLFjuN
app.jwt.expiration-ms=86400000

# ======================
# OPENAPI / SWAGGER
# ======================
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs

